// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj6ck-sacf4jKO9aPNwPBy3-skkGkM1WU',
    appId: '1:654349328745:android:fcf77053e8e98e7beb1df8',
    messagingSenderId: '654349328745',
    projectId: 'lenguajes-prueba',
    databaseURL: 'https://lenguajes-prueba-default-rtdb.firebaseio.com',
    storageBucket: 'lenguajes-prueba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA97ZvCjqGMMUrx0YcM28rW7DXoGzOekzk',
    appId: '1:654349328745:ios:5facf0f242c5cfb2eb1df8',
    messagingSenderId: '654349328745',
    projectId: 'lenguajes-prueba',
    databaseURL: 'https://lenguajes-prueba-default-rtdb.firebaseio.com',
    storageBucket: 'lenguajes-prueba.firebasestorage.app',
    iosBundleId: 'com.example.quickbitesPrueba',
  );
}
